### ISSUE TITLE
gLike seems incompatible with numcodecs>=0.16.0 and numpy>=2.0.0

### ISSUE THREAD

**Issue by stephenrong** [Ephraim-usc/glike#1]
Here are the errors

```
Command '['/home/srong/.conda/envs/ghist/bin/python3.13', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/home/srong/mnt/scratch/srong/tmpbxcqor0d', '--quiet', 'numpy>=1.14.5']' returned non-zero exit status 1.

ImportError: cannot import name 'cbuffer_sizes' from 'numcodecs.blosc' (/home/srong/.conda/envs/ghist_glike/lib/python3.12/site-packages/numcodecs/blosc.cpython-312-x86_64-linux-gnu.so). Did you mean: '_cbuffer_sizes'?

```
(Note that cbuffer_sizes was removed in numcodecs 0.16.0.)

It seems to work with numpy=1.26.4 and numcodes=0.15.1.

**Comment by Ephraim-usc** [comment]
Thanks @stephenrong for reporting this issue! We’ve found that NumPy 2.x introduces broad changes affecting SciPy, msprime, and—most challenging—our C extension module. We’re working toward upgrading gLike for full compatibility with NumPy 2.x. In the meantime, we recommend using NumPy 1.x for stable results.

Btw, gLike doesn't seem to be directly dependent on numcodecs.
